//---------------------------------------------------------------------------
// French Keyboard Layout without dead keys (WKL)
// Automatically generated from kbdfr.dll and then manually modified.
// Using dead keys for '~', '^', '`' is a pain for developers.
// We remove all dead keys and we remap some accentuated characters
// with AltGr or Shift-AltGr on some letters (see vk_to_wchar6).
//---------------------------------------------------------------------------

#define KBD_TYPE 4

#include <windows.h>
#include <kbd.h>
#include <dontuse.h>
#include "unicode.h"

//---------------------------------------------------------------------------
// Scan codes to key names
//---------------------------------------------------------------------------

static VSC_LPWSTR key_names[] = {
    {0x01, L"ECHAP"},
    {0x0E, L"RET.ARR"},
    {0x0F, L"TAB"},
    {0x1C, L"ENTREE"},
    {0x1D, L"CTRL"},
    {0x2A, L"MAJ"},
    {0x36, L"MAJ DROITE"},
    {0x37, L"* (PAVE NUM.)"},
    {0x38, L"ALT"},
    {0x39, L"ESPACE"},
    {0x3A, L"VERR.MAJ"},
    {0x3B, L"F1"},
    {0x3C, L"F2"},
    {0x3D, L"F3"},
    {0x3E, L"F4"},
    {0x3F, L"F5"},
    {0x40, L"F6"},
    {0x41, L"F7"},
    {0x42, L"F8"},
    {0x43, L"F9"},
    {0x44, L"F10"},
    {0x45, L"Pause"},
    {0x46, L"DEFIL"},
    {0x47, L"7 (PAVE NUM.)"},
    {0x48, L"8 (PAVE NUM.)"},
    {0x49, L"9 (PAVE NUM.)"},
    {0x4A, L"- (PAVE NUM.)"},
    {0x4B, L"4 (PAVE NUM.)"},
    {0x4C, L"5 (PAVE NUM.)"},
    {0x4D, L"6 (PAVE NUM.)"},
    {0x4E, L"+ (PAVE NUM.)"},
    {0x4F, L"1 (PAVE NUM.)"},
    {0x50, L"2 (PAVE NUM.)"},
    {0x51, L"3 (PAVE NUM.)"},
    {0x52, L"0 (PAVE NUM.)"},
    {0x53, L". (PAVE NUM.)"},
    {0x57, L"F11"},
    {0x58, L"F12"},
    {0x00, NULL}
};

//---------------------------------------------------------------------------
// Scan codes to key names (extended keypad)
//---------------------------------------------------------------------------

static VSC_LPWSTR key_names_ext[] = {
    {0x1C, L"ENTREE (PAVE NUM.)"},
    {0x1D, L"CTRL DROITE"},
    {0x35, L"/ (PAVE NUM.)"},
    {0x37, L"Impr.Ecran"},
    {0x38, L"ALT DROITE"},
    {0x45, L"Ver.Num"},
    {0x46, L"ATTN"},
    {0x47, L"ORIGINE"},
    {0x48, L"HAUT"},
    {0x49, L"PG.PREC"},
    {0x4B, L"GAUCHE"},
    {0x4D, L"DROITE"},
    {0x4F, L"FIN"},
    {0x50, L"BAS"},
    {0x51, L"PG.SUIV"},
    {0x52, L"INS"},
    {0x53, L"SUPPR"},
    {0x54, L"<00>"},
    {0x56, L"AIDE"},
    {0x5B, L"WINDOWS GAUCHE"},
    {0x5C, L"WINDOWS DROITE"},
    {0x5D, L"APPLICATION"},
    {0x00, NULL}
};

//---------------------------------------------------------------------------
// Names of dead keys
//---------------------------------------------------------------------------

static DEADKEY_LPWSTR key_names_dead[] = {
    L"\x0326"  L"COMMA BELOW"
    L"\x0335"  L"SHORT STROKE OVERLAY"
    L"\x0323"  L"DOT BELOW"
    L"\x0337"  L"SHORT SOLIDUS OVERLAY"
    L"^"       L"CIRCUMFLEX ACCENT"
    L"`"       L"GRAVE ACCENT"
    L"~"       L"TILDE"
    L"\x00a4"  L"CURRENCY SIGN"
    L"\x00a8"  L"DIAERESIS"
    L"\x00af"  L"MACRON"
    L"\x0311"  L"INVERTED BREVE"
    L"\x00b4"  L"ACUTE ACCENT"
    L"\x00b5"  L"MICRO SIGN"
    L"\x00b8"  L"CEDILLA"
    L"\x017f"  L"LATIN SMALL LETTER LONG S"
    L"\x02c7"  L"CARON"
    L"\x02cd"  L"MACRON BELOW"
    L"\x02d8"  L"BREVE"
    L"\x02d9"  L"DOT ABOVE"
    L"\x02da"  L"RING ABOVE"
    L"\x02db"  L"OGONEK"
    L"\x02dd"  L"DOUBLE ACUTE ACCENT"
    L"\x02f5"  L"DOUBLE GRAVE ACCENT"
    NULL
};

//---------------------------------------------------------------------------
// Scan code to virtual key conversion table
//---------------------------------------------------------------------------

static USHORT scancode_to_vk[] = {
    /* 00 */ VK__none_,
    /* 01 */ VK_ESCAPE,
    /* 02 */ '1',
    /* 03 */ '2',
    /* 04 */ '3',
    /* 05 */ '4',
    /* 06 */ '5',
    /* 07 */ '6',
    /* 08 */ '7',
    /* 09 */ '8',
    /* 0A */ '9',
    /* 0B */ '0',
    /* 0C */ VK_OEM_4,
    /* 0D */ VK_OEM_6,
    /* 0E */ VK_BACK,
    /* 0F */ VK_TAB,
    /* 10 */ 'A',
    /* 11 */ 'Z',
    /* 12 */ 'E',
    /* 13 */ 'R',
    /* 14 */ 'T',
    /* 15 */ 'Y',
    /* 16 */ 'U',
    /* 17 */ 'I',
    /* 18 */ 'O',
    /* 19 */ 'P',
    /* 1A */ VK_OEM_MINUS,
    /* 1B */ VK_OEM_PLUS,
    /* 1C */ VK_RETURN,
    /* 1D */ VK_LCONTROL,
    /* 1E */ 'Q',
    /* 1F */ 'S',
    /* 20 */ 'D',
    /* 21 */ 'F',
    /* 22 */ 'G',
    /* 23 */ 'H',
    /* 24 */ 'J',
    /* 25 */ 'K',
    /* 26 */ 'L',
    /* 27 */ 'M',
    /* 28 */ VK_OEM_3,
    /* 29 */ VK_OEM_7,
    /* 2A */ VK_LSHIFT,
    /* 2B */ VK_OEM_5,
    /* 2C */ 'W',
    /* 2D */ 'X',
    /* 2E */ 'C',
    /* 2F */ 'V',
    /* 30 */ 'B',
    /* 31 */ 'N',
    /* 32 */ VK_OEM_PERIOD,
    /* 33 */ VK_OEM_COMMA,
    /* 34 */ VK_OEM_2,
    /* 35 */ VK_OEM_8,
    /* 36 */ VK_RSHIFT | KBDEXT,
    /* 37 */ VK_MULTIPLY | KBDMULTIVK,
    /* 38 */ VK_LMENU,
    /* 39 */ VK_SPACE,
    /* 3A */ VK_CAPITAL,
    /* 3B */ VK_F1,
    /* 3C */ VK_F2,
    /* 3D */ VK_F3,
    /* 3E */ VK_F4,
    /* 3F */ VK_F5,
    /* 40 */ VK_F6,
    /* 41 */ VK_F7,
    /* 42 */ VK_F8,
    /* 43 */ VK_F9,
    /* 44 */ VK_F10,
    /* 45 */ VK_NUMLOCK | KBDEXT | KBDMULTIVK,
    /* 46 */ VK_SCROLL | KBDMULTIVK,
    /* 47 */ VK_HOME | KBDSPECIAL | KBDNUMPAD,
    /* 48 */ VK_UP | KBDSPECIAL | KBDNUMPAD,
    /* 49 */ VK_PRIOR | KBDSPECIAL | KBDNUMPAD,
    /* 4A */ VK_SUBTRACT,
    /* 4B */ VK_LEFT | KBDSPECIAL | KBDNUMPAD,
    /* 4C */ VK_CLEAR | KBDSPECIAL | KBDNUMPAD,
    /* 4D */ VK_RIGHT | KBDSPECIAL | KBDNUMPAD,
    /* 4E */ VK_ADD,
    /* 4F */ VK_END | KBDSPECIAL | KBDNUMPAD,
    /* 50 */ VK_DOWN | KBDSPECIAL | KBDNUMPAD,
    /* 51 */ VK_NEXT | KBDSPECIAL | KBDNUMPAD,
    /* 52 */ VK_INSERT | KBDSPECIAL | KBDNUMPAD,
    /* 53 */ VK_DELETE | KBDSPECIAL | KBDNUMPAD,
    /* 54 */ VK_SNAPSHOT,
    /* 55 */ VK__none_,
    /* 56 */ VK_OEM_102,
    /* 57 */ VK_F11,
    /* 58 */ VK_F12,
    /* 59 */ VK_CLEAR,
    /* 5A */ VK_OEM_WSCTRL,
    /* 5B */ VK_OEM_FINISH,
    /* 5C */ VK_OEM_JUMP,
    /* 5D */ VK_EREOF,
    /* 5E */ VK_OEM_BACKTAB,
    /* 5F */ VK_OEM_AUTO,
    /* 60 */ VK__none_,
    /* 61 */ VK__none_,
    /* 62 */ VK_ZOOM,
    /* 63 */ VK_HELP,
    /* 64 */ VK_F13,
    /* 65 */ VK_F14,
    /* 66 */ VK_F15,
    /* 67 */ VK_F16,
    /* 68 */ VK_F17,
    /* 69 */ VK_F18,
    /* 6A */ VK_F19,
    /* 6B */ VK_F20,
    /* 6C */ VK_F21,
    /* 6D */ VK_F22,
    /* 6E */ VK_F23,
    /* 6F */ VK_OEM_PA3,
    /* 70 */ VK__none_,
    /* 71 */ VK_OEM_RESET,
    /* 72 */ VK__none_,
    /* 73 */ 0x00C1,
    /* 74 */ VK__none_,
    /* 75 */ VK__none_,
    /* 76 */ VK_F24,
    /* 77 */ VK__none_,
    /* 78 */ VK__none_,
    /* 79 */ VK__none_,
    /* 7A */ VK__none_,
    /* 7B */ VK_OEM_PA1,
    /* 7C */ VK_TAB,
    /* 7D */ VK__none_,
    /* 7E */ 0x00C2,
};

//---------------------------------------------------------------------------
// Scan code to virtual key conversion table (scancodes with E0 prefix)
//---------------------------------------------------------------------------

static VSC_VK scancode_to_vk_e0[] = {
    {0x10, VK_MEDIA_PREV_TRACK | KBDEXT},
    {0x19, VK_MEDIA_NEXT_TRACK | KBDEXT},
    {0x1D, VK_RCONTROL | KBDEXT},
    {0x20, VK_VOLUME_MUTE | KBDEXT},
    {0x21, VK_LAUNCH_APP2 | KBDEXT},
    {0x22, VK_MEDIA_PLAY_PAUSE | KBDEXT},
    {0x24, VK_MEDIA_STOP | KBDEXT},
    {0x2E, VK_VOLUME_DOWN | KBDEXT},
    {0x30, VK_VOLUME_UP | KBDEXT},
    {0x32, VK_BROWSER_HOME | KBDEXT},
    {0x35, VK_DIVIDE | KBDEXT},
    {0x37, VK_SNAPSHOT | KBDEXT},
    {0x38, VK_RMENU | KBDEXT},
    {0x47, VK_HOME | KBDEXT},
    {0x48, VK_UP | KBDEXT},
    {0x49, VK_PRIOR | KBDEXT},
    {0x4B, VK_LEFT | KBDEXT},
    {0x4D, VK_RIGHT | KBDEXT},
    {0x4F, VK_END | KBDEXT},
    {0x50, VK_DOWN | KBDEXT},
    {0x51, VK_NEXT | KBDEXT},
    {0x52, VK_INSERT | KBDEXT},
    {0x53, VK_DELETE | KBDEXT},
    {0x5B, VK_LWIN | KBDEXT},
    {0x5C, VK_RWIN | KBDEXT},
    {0x5D, VK_APPS | KBDEXT},
    {0x5F, VK_SLEEP | KBDEXT},
    {0x65, VK_BROWSER_SEARCH | KBDEXT},
    {0x66, VK_BROWSER_FAVORITES | KBDEXT},
    {0x67, VK_BROWSER_REFRESH | KBDEXT},
    {0x68, VK_BROWSER_STOP | KBDEXT},
    {0x69, VK_BROWSER_FORWARD | KBDEXT},
    {0x6A, VK_BROWSER_BACK | KBDEXT},
    {0x6B, VK_LAUNCH_APP1 | KBDEXT},
    {0x6C, VK_LAUNCH_MAIL | KBDEXT},
    {0x6D, VK_LAUNCH_MEDIA_SELECT | KBDEXT},
    {0x1C, VK_RETURN | KBDEXT},
    {0x46, VK_CANCEL | KBDEXT},
    {0x00, 0x0000}
};

//---------------------------------------------------------------------------
// Scan code to virtual key conversion table (scancodes with E1 prefix)
//---------------------------------------------------------------------------

static VSC_VK scancode_to_vk_e1[] = {
    {0x1D, VK_PAUSE},
    {0x00, 0x0000}
};

//---------------------------------------------------------------------------
// Associate a virtual key with a modifier bitmask
//---------------------------------------------------------------------------

static VK_TO_BIT vk_to_bits[] = {
    {VK_SHIFT,   KBDSHIFT},
    {VK_CONTROL, KBDCTRL},
    {VK_MENU,    KBDALT},
    {0,          0}
};

//---------------------------------------------------------------------------
// Map character modifier bits to modification number
//---------------------------------------------------------------------------

static MODIFIERS char_modifiers = {
    .pVkToBit    = vk_to_bits,
    .wMaxModBits = 7,
    .ModNumber   = {
        0,            // 000 = <none>
        1,            // 001 = Shift
        2,            // 010 = Control
        4,            // 011 = Shift Control
        SHFT_INVALID, // 100 = Alt
        SHFT_INVALID, // 101 = Shift Alt
        3,            // 110 = Control Alt (AltGr)
        5,            // 111 = Shift Control Alt (Shift AltGr)
    }
};

//---------------------------------------------------------------------------
// Virtual Key to WCHAR translations for 3 shift states
//
// WCH_NONE WCH_DEAD
//---------------------------------------------------------------------------

static VK_TO_WCHARS3 vk_to_wchar3[] = {
    //                            Shift         Ctrl
    //                            -----         ----
    {VK_BACK,    0,      {UC_BS,  UC_BS,        UC_DEL}},
    {VK_ESCAPE,  0,      {UC_ESC, UC_ESC,       UC_ESC}},
    {VK_RETURN,  0,      {L'\r',  L'\r',        L'\n'}},
    {VK_CANCEL,  0,      {UC_ETX, UC_ETX,       UC_ETX}},
    {0,          0,      0,       0,            0}
};

//---------------------------------------------------------------------------
// Virtual Key to WCHAR translations for 4 shift states
//---------------------------------------------------------------------------

static VK_TO_WCHARS4 vk_to_wchar4[] = {
    //                                          Shift         Ctrl       AltGr
    //                                          -----         ----       -----
    {'7',            0,       {UC_S_LEFT_QUOT,  L'7',         WCH_NONE,  WCH_DEAD}},
    {VK__none_,      0,       {WCH_NONE,        WCH_NONE,     WCH_NONE,  UC_MACRON}},
    {VK_OEM_6,       0,       {WCH_DEAD,        WCH_DEAD,     UC_ESC,    WCH_DEAD}},
    {VK__none_,      0,       {0x017f,          UC_CURRENCY,  WCH_NONE,  UC_MICRO}},
    {'Z',            CAPLOK,  {L'z',            L'Z',         WCH_NONE,  UC_POUND}},
    {'E',            CAPLOK,  {L'e',            L'E',         WCH_NONE,  UC_EURO}},
    {'D',            CAPLOK,  {L'd',            L'D',         WCH_NONE,  L'$'}},
    {'H',            CAPLOK,  {L'h',            L'H',         WCH_NONE,  WCH_DEAD}},
    {VK__none_,      0,       {WCH_NONE,        WCH_NONE,     WCH_NONE,  0x02cd}},
    {'K',            CAPLOK,  {L'k',            L'K',         WCH_NONE,  WCH_DEAD}},
    {VK__none_,      0,       {WCH_NONE,        WCH_NONE,     WCH_NONE,  UC_COMB_SHORT_SOLIDUS_OVERLAY}},
    {'L',            CAPLOK,  {L'l',            L'L',         WCH_NONE,  L'|'}},
    {'M',            CAPLOK,  {L'm',            L'M',         WCH_NONE,  UC_INFINITY}},
    {'X',            CAPLOK,  {L'x',            L'X',         WCH_NONE,  UC_COPYRIGHT}},
    {'B',            CAPLOK,  {L'b',            L'B',         WCH_NONE,  WCH_DEAD}},
    {VK__none_       0,       {WCH_NONE,        WCH_NONE,     WCH_NONE,  UC_COMB_SHORT_STROKE_OVERLAY}},
    {'N',            CAPLOK,  {L'n',            L'N',         WCH_NONE,  WCH_DEAD}},
    {VK__none_       0,       {WCH_NONE,        WCH_NONE,     WCH_NONE,  L'~'}},
    {VK_OEM_PERIOD,  0,       {L'.',            L'?',         WCH_NONE,  UC_INV_QUESTION}},
    {VK_OEM_2,       0,       {L':',            UC_ELLIPSIS,  WCH_NONE,  UC_MIDDOT}},
    {0,              0,       0,                0,            0,         0}
};

//---------------------------------------------------------------------------
// Virtual Key to WCHAR translations for 5 shift states
//---------------------------------------------------------------------------

static VK_TO_WCHARS5 vk_to_wchar5[] = {
    //                               Shift     Ctrl      AltGr       Shift/Ctrl
    //                               -----     ----      -----       ----------
    {'5',       0, {WCH_DEAD,        L'5',     WCH_NONE, WCH_DEAD,   UC_ESC}},
    {VK__none_, 0, {UC_DIAERESIS,    WCH_NONE, WCH_NONE, UC_CARON,   WCH_NONE}},
    {'8',       0, {UC_S_RIGHT_QUOT, L'8',     WCH_NONE, UC_EM_DASH, UC_FS}}, 
    {0,         0, 0,                0,        0,        0,          0}
};

//---------------------------------------------------------------------------
// Virtual Key to WCHAR translations for 6 shift states
//---------------------------------------------------------------------------

static VK_TO_WCHARS6 vk_to_wchar6[] = {
    //                                                            Shift           Ctrl       AltGr                Shift/Ctrl Shift/AltGr
    //                                                            -----           ----       -----                ---------- -----------
    {'1',           SGCap,               {UC_LOWER_A_GRAVE,       L'1',           WCH_NONE,  UC_SECTION,          WCH_NONE,  UC_UPPER_A_GRAVE}},
    {VK__none_,     0,                   {UC_UPPER_A_GRAVE,       L'1',           WCH_NONE,  WCH_NONE,            WCH_NONE,  WCH_NONE}},
    {'2',           SGCap,               {UC_LOWER_E_ACUTE,       L'2',           WCH_NONE,  WCH_DEAD,            WCH_NONE,  UC_UPPER_E_ACUTE}},
    {VK__none_,     0,                   {UC_UPPER_E_ACUTE,       L'2',           WCH_NONE,  UC_ACUTE,            WCH_NONE,  WCH_NONE}},
    {'3',           SGCap,               {UC_LOWER_E_GRAVE,       L'3',           WCH_NONE,  WCH_DEAD,            WCH_NONE,  UC_UPPER_E_GRAVE}},
    {VK__none_,     0,                   {UC_UPPER_E_GRAVE,       L'3',           WCH_NONE,  L'`',                WCH_NONE,  WCH_NONE}},
    {'4',           SGCap,               {UC_LOWER_E_CIRCUMFLEX,  L'4',           WCH_NONE,  WCH_DEAD,            WCH_NONE,  UC_UPPER_E_CIRCUMFLEX}},
    {VK__none_,     0,                   {UC_UPPER_E_CIRCUMFLEX,  L'4',           WCH_NONE,  L'^',                WCH_NONE,  WCH_NONE}},
    {'6',           0,                   {L'&',                   L'6',           WCH_NONE,  WCH_DEAD,            UC_US,     WCH_DEAD}},
    {VK__none_,     0,                   {WCH_NONE,               WCH_NONE,       WCH_NONE,  UC_DOUBLE_ACUTE,     WCH_NONE,  0x02f5}},
    {'9',           0,                   {UC_DA_LEFT_QUOT,        L'9',           WCH_NONE,  UC_SA_LEFT_QUOT,     UC_RS,     UC_D_LEFT_QUOT}},
    {'0',           0,                   {UC_DA_RIGHT_QUOT,       L'0',           UC_NULL,   UC_SA_RIGHT_QUOT,    WCH_NONE,  UC_D_RIGHT_QUOT}},
    {VK_OEM_4,      0,                   {L'\'',                  L'"',           WCH_NONE,  UC_DEGREE,           WCH_NONE,  WCH_DEAD}},
    {VK__none_,     0,                   {WCH_NONE,               WCH_NONE,       WCH_NONE,  WCH_NONE,            WCH_NONE,  0x02da}},
    {'A',           CAPLOK|CAPLOKALTGR,  {L'a',                   L'A',           WCH_NONE,  UC_LOWER_AE,         WCH_NONE,  UC_UPPER_AE}},
    {'R',           CAPLOK,              {L'r',                   L'R',           WCH_NONE,  L'{',                WCH_NONE,  UC_REGISTERED}},
    {'T',           CAPLOK,              {L't',                   L'T',           WCH_NONE,  L'}',                WCH_NONE,  UC_TRADE}},
    {'U',           CAPLOK|CAPLOKALTGR,  {L'u',                   L'U',           WCH_NONE,  UC_LOWER_U_GRAVE,    WCH_NONE,  UC_UPPER_U_GRAVE}},
    {'I',           CAPLOK,              {L'i',                   L'I',           WCH_NONE,  WCH_DEAD,            WCH_NONE,  WCH_DEAD}},
    {VK__none_,     0,                   {WCH_NONE,               WCH_NONE,       WCH_NONE,  UC_DOT_ABOVE,        WCH_NONE,  UC_COMB_DOT_BELOW}},
    {'O',           CAPLOK|CAPLOKALTGR,  {L'o',                   L'O',           WCH_NONE,  UC_LOWER_OE,         WCH_NONE,  UC_UPPER_OE}},
    {'P',           CAPLOK,              {L'p',                   L'P',           WCH_NONE,  L'%',                WCH_NONE,  UC_PER_MILLE}},
    {VK_OEM_MINUS,  0,                   {L'-',                   UC_EN_DASH,     WCH_NONE,  UC_MINUS,            WCH_NONE,  0x2011}},
    {VK_OEM_PLUS,   0,                   {L'+',                   UC_PLUS_MINUS,  WCH_NONE,  UC_DAGGER,           WCH_NONE,  UC_D_DAGGER}},
    {'Q',           CAPLOK|CAPLOKALTGR,  {L'q',                   L'Q',           WCH_NONE,  UC_LOWER_THETA,      WCH_NONE,  0x03f4}},
    {'S',           CAPLOK|CAPLOKALTGR,  {L's',                   L'S',           WCH_NONE,  UC_LOWER_SHARP_S,    WCH_NONE,  0x1e9e}},
    {'F',           CAPLOK,              {L'f',                   L'F',           WCH_NONE,  L'(',                WCH_NONE,  L'['}},
    {'G',           CAPLOK,              {L'g',                   L'G',           WCH_NONE,  L')',                WCH_NONE,  L']'}},
    {VK_OEM_3,      0,                   {L'/',                   L'\\',          WCH_NONE,  UC_DIVISION,         WCH_NONE,  UC_SQUARE_ROOT}},
    {VK_OEM_7,      0,                   {L'@',                   L'#',           WCH_NONE,  WCH_DEAD,            WCH_NONE,  WCH_DEAD}},
    {VK__none_,     0,                   {WCH_NONE,               WCH_NONE,       WCH_NONE,  UC_BREVE,            WCH_NONE,  UC_COMB_INV_BREVE}},
    {VK_OEM_5,      0,                   {L'*',                   UC_FRAC_1_2,    UC_FS,     UC_MULTIPLICATION,   WCH_NONE,  UC_FRAC_1_4}},
    {VK_OEM_102,    0,                   {L'<',                   L'>',           UC_FS,     0x2a7d,              WCH_NONE,  0x2a7e}},
    {'W',           CAPLOK|CAPLOKALTGR,  {L'w',                   L'W',           WCH_NONE,  0x0292,              WCH_NONE,  0x01b7}},
    {'C',           CAPLOK|CAPLOKALTGR,  {L'c',                   L'C',           WCH_NONE,  UC_LOWER_C_CEDILLA,  WCH_NONE,  UC_UPPER_C_CEDILLA}},
    {'V',           CAPLOK,              {L'v',                   L'V',           WCH_NONE,  WCH_DEAD,            WCH_NONE,  WCH_DEAD}},
    {VK__none_,     CAPLOK,              {WCH_NONE,               WCH_NONE,       WCH_NONE,  UC_CEDILLA,          WCH_NONE,  UC_OGONEK}},
    {VK_OEM_COMMA,  0,                   {L',',                   L'!',           WCH_NONE,  UC_INV_EXCL,         WCH_NONE,  WCH_DEAD}},
    {VK__none_,     0,                   {WCH_NONE,               WCH_NONE,       WCH_NONE,  WCH_NONE,            WCH_NONE,  UC_COMB_COMMA_BELOW}},
    {VK_OEM_8,      0,                   {L';',                   L'=',           UC_GS,     0x2243,              WCH_NONE,  UC_NOT_EQUAL}},
    {VK_SPACE,      0,                   {L' ',                   L'_',           L' ',      UC_NBSP,             WCH_NONE,  UC_NNBSP}},
    {0,             0,                   0,                       0,              0,         0,                   0,         0}
};

//---------------------------------------------------------------------------
// Virtual Key to WCHAR translations for 2 shift states
//---------------------------------------------------------------------------

static VK_TO_WCHARS2 vk_to_wchar2[] = {
    //                                         Shift
    //                                         -----
    {'Y',           CAPLOK, {L'y',             L'Y'}},
    {'J',           CAPLOK, {L'j',             L'J'}},
    {VK_DECIMAL,    0,      {L'.',             L'.'}},
    {VK_TAB,        0,      {L'\t',            L'\t'}},
    {VK_ADD,        0,      {L'+',             L'+'}},
    {VK_DIVIDE,     0,      {L'/',             L'/'}},
    {VK_MULTIPLY,   0,      {L'*',             L'*'}},
    {VK_SUBTRACT,   0,      {L'-',             L'-'}},
    {0,             0,      0,                 0}
};

//---------------------------------------------------------------------------
// Virtual Key to WCHAR translations for 1 shift states
//---------------------------------------------------------------------------

static VK_TO_WCHARS1 vk_to_wchar1[] = {
    {VK_NUMPAD0, 0,    {L'0'}},
    {VK_NUMPAD1, 0,    {L'1'}},
    {VK_NUMPAD2, 0,    {L'2'}},
    {VK_NUMPAD3, 0,    {L'3'}},
    {VK_NUMPAD4, 0,    {L'4'}},
    {VK_NUMPAD5, 0,    {L'5'}},
    {VK_NUMPAD6, 0,    {L'6'}},
    {VK_NUMPAD7, 0,    {L'7'}},
    {VK_NUMPAD8, 0,    {L'8'}},
    {VK_NUMPAD9, 0,    {L'9'}},
    {0,          0,    0}
};

//---------------------------------------------------------------------------
// Virtual Key to WCHAR translations with shift states
//---------------------------------------------------------------------------

static VK_TO_WCHAR_TABLE vk_to_wchar[] = {
    {(PVK_TO_WCHARS1)vk_to_wchar3, 3, sizeof(vk_to_wchar3[0])},
    {(PVK_TO_WCHARS1)vk_to_wchar4, 4, sizeof(vk_to_wchar4[0])},
    {(PVK_TO_WCHARS1)vk_to_wchar5, 5, sizeof(vk_to_wchar5[0])},
    {(PVK_TO_WCHARS1)vk_to_wchar6, 6, sizeof(vk_to_wchar6[0])},
    {(PVK_TO_WCHARS1)vk_to_wchar2, 2, sizeof(vk_to_wchar2[0])},
    {(PVK_TO_WCHARS1)vk_to_wchar1, 1, sizeof(vk_to_wchar1[0])},
    {NULL,                         0, 0}
};

//---------------------------------------------------------------------------
// Dead keys sequences translations
//---------------------------------------------------------------------------

static DEADKEY dead_keys[] = {
    //              Accent        Composed               Flags
    //              ------        --------               -----
    DEADTRANS(L'e', UC_ACUTE,     UC_LOWER_E_ACUTE,      0x0000),
    DEADTRANS(L'S', UC_COMB_COMMA_BELOW, UC_UPPER_S_COMMA_BELOW, 0x0000),
    DEADTRANS(L'T', UC_COMB_COMMA_BELOW, UC_UPPER_T_COMMA_BELOW, 0x0000),
    DEADTRANS(L's', UC_COMB_COMMA_BELOW, UC_LOWER_S_COMMA_BELOW, 0x0000),
    DEADTRANS(L't', UC_COMB_COMMA_BELOW, UC_LOWER_T_COMMA_BELOW, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_COMB_COMMA_BELOW, UC_COMB_COMMA_BELOW, 0x0000),
    DEADTRANS(UC_MICRO, UC_COMB_COMMA_BELOW, UC_COMB_COMMA_BELOW, 0x0000),
    DEADTRANS(0x017f, UC_COMB_COMMA_BELOW, UC_COMB_COMMA_BELOW, 0x0000),
    DEADTRANS(UC_NBSP, UC_COMB_COMMA_BELOW, UC_COMB_COMMA_BELOW, 0x0000),
    DEADTRANS(UC_NNBSP, UC_COMB_COMMA_BELOW, UC_COMB_COMMA_BELOW, 0x0000),
    DEADTRANS(L' ', UC_COMB_COMMA_BELOW, UC_COMB_COMMA_BELOW, 0x0000),
    DEADTRANS(L'B', UC_COMB_SHORT_STROKE_OVERLAY, 0x0243, 0x0000),
    DEADTRANS(L'D', UC_COMB_SHORT_STROKE_OVERLAY, UC_UPPER_D_STROKE, 0x0000),
    DEADTRANS(L'G', UC_COMB_SHORT_STROKE_OVERLAY, 0x01e4, 0x0000),
    DEADTRANS(L'H', UC_COMB_SHORT_STROKE_OVERLAY, UC_UPPER_H_STROKE, 0x0000),
    DEADTRANS(L'I', UC_COMB_SHORT_STROKE_OVERLAY, 0x0197, 0x0000),
    DEADTRANS(L'J', UC_COMB_SHORT_STROKE_OVERLAY, 0x0248, 0x0000),
    DEADTRANS(L'L', UC_COMB_SHORT_STROKE_OVERLAY, 0x023d, 0x0000),
    DEADTRANS(L'R', UC_COMB_SHORT_STROKE_OVERLAY, 0x024c, 0x0000),
    DEADTRANS(L'T', UC_COMB_SHORT_STROKE_OVERLAY, UC_UPPER_T_STROKE, 0x0000),
    DEADTRANS(L'U', UC_COMB_SHORT_STROKE_OVERLAY, 0x0244, 0x0000),
    DEADTRANS(L'Y', UC_COMB_SHORT_STROKE_OVERLAY, 0x024e, 0x0000),
    DEADTRANS(L'Z', UC_COMB_SHORT_STROKE_OVERLAY, 0x01b5, 0x0000),
    DEADTRANS(L'b', UC_COMB_SHORT_STROKE_OVERLAY, 0x0180, 0x0000),
    DEADTRANS(L'd', UC_COMB_SHORT_STROKE_OVERLAY, UC_LOWER_D_STROKE, 0x0000),
    DEADTRANS(L'g', UC_COMB_SHORT_STROKE_OVERLAY, 0x01e5, 0x0000),
    DEADTRANS(L'h', UC_COMB_SHORT_STROKE_OVERLAY, UC_LOWER_H_STROKE, 0x0000),
    DEADTRANS(L'j', UC_COMB_SHORT_STROKE_OVERLAY, 0x0249, 0x0000),
    DEADTRANS(L'l', UC_COMB_SHORT_STROKE_OVERLAY, 0x019a, 0x0000),
    DEADTRANS(L'r', UC_COMB_SHORT_STROKE_OVERLAY, 0x024d, 0x0000),
    DEADTRANS(L't', UC_COMB_SHORT_STROKE_OVERLAY, UC_LOWER_T_STROKE, 0x0000),
    DEADTRANS(L'y', UC_COMB_SHORT_STROKE_OVERLAY, 0x024f, 0x0000),
    DEADTRANS(L'z', UC_COMB_SHORT_STROKE_OVERLAY, 0x01b6, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_COMB_SHORT_STROKE_OVERLAY, UC_COMB_SHORT_STROKE_OVERLAY, 0x0000),
    DEADTRANS(UC_MICRO, UC_COMB_SHORT_STROKE_OVERLAY, UC_COMB_SHORT_STROKE_OVERLAY, 0x0000),
    DEADTRANS(0x017f, UC_COMB_SHORT_STROKE_OVERLAY, UC_COMB_SHORT_STROKE_OVERLAY, 0x0000),
    DEADTRANS(UC_NBSP, UC_COMB_SHORT_STROKE_OVERLAY, UC_COMB_SHORT_STROKE_OVERLAY, 0x0000),
    DEADTRANS(UC_NNBSP, UC_COMB_SHORT_STROKE_OVERLAY, UC_COMB_SHORT_STROKE_OVERLAY, 0x0000),
    DEADTRANS(L' ', UC_COMB_SHORT_STROKE_OVERLAY, UC_COMB_SHORT_STROKE_OVERLAY, 0x0000),
    DEADTRANS(L'A', UC_COMB_DOT_BELOW, 0x1ea0, 0x0000),
    DEADTRANS(L'B', UC_COMB_DOT_BELOW, 0x1e04, 0x0000),
    DEADTRANS(L'D', UC_COMB_DOT_BELOW, 0x1e0c, 0x0000),
    DEADTRANS(L'E', UC_COMB_DOT_BELOW, 0x1eb8, 0x0000),
    DEADTRANS(L'H', UC_COMB_DOT_BELOW, 0x1e24, 0x0000),
    DEADTRANS(L'I', UC_COMB_DOT_BELOW, 0x1eca, 0x0000),
    DEADTRANS(L'K', UC_COMB_DOT_BELOW, 0x1e32, 0x0000),
    DEADTRANS(L'L', UC_COMB_DOT_BELOW, 0x1e36, 0x0000),
    DEADTRANS(L'M', UC_COMB_DOT_BELOW, 0x1e42, 0x0000),
    DEADTRANS(L'N', UC_COMB_DOT_BELOW, 0x1e46, 0x0000),
    DEADTRANS(L'O', UC_COMB_DOT_BELOW, 0x1ecc, 0x0000),
    DEADTRANS(L'R', UC_COMB_DOT_BELOW, 0x1e5a, 0x0000),
    DEADTRANS(L'S', UC_COMB_DOT_BELOW, 0x1e62, 0x0000),
    DEADTRANS(L'T', UC_COMB_DOT_BELOW, 0x1e6c, 0x0000),
    DEADTRANS(L'U', UC_COMB_DOT_BELOW, 0x1ee4, 0x0000),
    DEADTRANS(L'V', UC_COMB_DOT_BELOW, 0x1e7e, 0x0000),
    DEADTRANS(L'W', UC_COMB_DOT_BELOW, 0x1e88, 0x0000),
    DEADTRANS(L'Y', UC_COMB_DOT_BELOW, 0x1ef4, 0x0000),
    DEADTRANS(L'Z', UC_COMB_DOT_BELOW, 0x1e92, 0x0000),
    DEADTRANS(L'a', UC_COMB_DOT_BELOW, 0x1ea1, 0x0000),
    DEADTRANS(L'b', UC_COMB_DOT_BELOW, 0x1e05, 0x0000),
    DEADTRANS(L'd', UC_COMB_DOT_BELOW, 0x1e0d, 0x0000),
    DEADTRANS(L'e', UC_COMB_DOT_BELOW, 0x1eb9, 0x0000),
    DEADTRANS(L'h', UC_COMB_DOT_BELOW, 0x1e25, 0x0000),
    DEADTRANS(L'i', UC_COMB_DOT_BELOW, 0x1ecb, 0x0000),
    DEADTRANS(L'k', UC_COMB_DOT_BELOW, 0x1e33, 0x0000),
    DEADTRANS(L'l', UC_COMB_DOT_BELOW, 0x1e37, 0x0000),
    DEADTRANS(L'm', UC_COMB_DOT_BELOW, 0x1e43, 0x0000),
    DEADTRANS(L'n', UC_COMB_DOT_BELOW, 0x1e47, 0x0000),
    DEADTRANS(L'o', UC_COMB_DOT_BELOW, 0x1ecd, 0x0000),
    DEADTRANS(L'r', UC_COMB_DOT_BELOW, 0x1e5b, 0x0000),
    DEADTRANS(L's', UC_COMB_DOT_BELOW, 0x1e63, 0x0000),
    DEADTRANS(L't', UC_COMB_DOT_BELOW, 0x1e6d, 0x0000),
    DEADTRANS(L'u', UC_COMB_DOT_BELOW, 0x1ee5, 0x0000),
    DEADTRANS(L'v', UC_COMB_DOT_BELOW, 0x1e7f, 0x0000),
    DEADTRANS(L'w', UC_COMB_DOT_BELOW, 0x1e89, 0x0000),
    DEADTRANS(L'y', UC_COMB_DOT_BELOW, 0x1ef5, 0x0000),
    DEADTRANS(L'z', UC_COMB_DOT_BELOW, 0x1e93, 0x0000),
    DEADTRANS(UC_UPPER_E_CIRCUMFLEX, UC_COMB_DOT_BELOW, 0x1ec6, 0x0000),
    DEADTRANS(UC_LOWER_E_CIRCUMFLEX, UC_COMB_DOT_BELOW, 0x1ec7, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_COMB_DOT_BELOW, UC_COMB_DOT_BELOW, 0x0000),
    DEADTRANS(UC_MICRO, UC_COMB_DOT_BELOW, UC_COMB_DOT_BELOW, 0x0000),
    DEADTRANS(0x017f, UC_COMB_DOT_BELOW, UC_COMB_DOT_BELOW, 0x0000),
    DEADTRANS(UC_NBSP, UC_COMB_DOT_BELOW, UC_COMB_DOT_BELOW, 0x0000),
    DEADTRANS(UC_NNBSP, UC_COMB_DOT_BELOW, UC_COMB_DOT_BELOW, 0x0000),
    DEADTRANS(L' ', UC_COMB_DOT_BELOW, UC_COMB_DOT_BELOW, 0x0000),
    DEADTRANS(L'<', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x226e, 0x0000),
    DEADTRANS(L'=', UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_NOT_EQUAL, 0x0000),
    DEADTRANS(L'>', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x226f, 0x0000),
    DEADTRANS(L'A', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x023a, 0x0000),
    DEADTRANS(L'C', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x023b, 0x0000),
    DEADTRANS(L'E', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x0246, 0x0000),
    DEADTRANS(L'L', UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_UPPER_L_STROKE, 0x0000),
    DEADTRANS(L'O', UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_UPPER_O_STROKE, 0x0000),
    DEADTRANS(L'T', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x023e, 0x0000),
    DEADTRANS(L'c', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x023c, 0x0000),
    DEADTRANS(L'e', UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x0247, 0x0000),
    DEADTRANS(L'l', UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_LOWER_L_STROKE, 0x0000),
    DEADTRANS(L'o', UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_LOWER_O_STROKE, 0x0000),
    DEADTRANS(0x017f, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x1e9c, 0x0000),
    DEADTRANS(0x2243, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x2244, 0x0000),
    DEADTRANS(0x2a7d, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x2270, 0x0000),
    DEADTRANS(0x2a7e, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x2271, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x0000),
    DEADTRANS(UC_MICRO, UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x0000),
    DEADTRANS(UC_NBSP, UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x0000),
    DEADTRANS(UC_NNBSP, UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x0000),
    DEADTRANS(L' ', UC_COMB_SHORT_SOLIDUS_OVERLAY, UC_COMB_SHORT_SOLIDUS_OVERLAY, 0x0000),
    DEADTRANS(L'(', L'^', 0x207d, 0x0000),
    DEADTRANS(L')', L'^', 0x207e, 0x0000),
    DEADTRANS(L'+', L'^', 0x207a, 0x0000),
    DEADTRANS(L'-', L'^', 0x207b, 0x0000),
    DEADTRANS(L'0', L'^', 0x2070, 0x0000),
    DEADTRANS(L'1', L'^', UC_SUP1, 0x0000),
    DEADTRANS(L'2', L'^', UC_SUP2, 0x0000),
    DEADTRANS(L'3', L'^', UC_SUP3, 0x0000),
    DEADTRANS(L'4', L'^', 0x2074, 0x0000),
    DEADTRANS(L'5', L'^', 0x2075, 0x0000),
    DEADTRANS(L'6', L'^', 0x2076, 0x0000),
    DEADTRANS(L'7', L'^', 0x2077, 0x0000),
    DEADTRANS(L'8', L'^', 0x2078, 0x0000),
    DEADTRANS(L'9', L'^', 0x2079, 0x0000),
    DEADTRANS(L'=', L'^', 0x207c, 0x0000),
    DEADTRANS(L'A', L'^', UC_UPPER_A_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'C', L'^', UC_UPPER_C_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'E', L'^', UC_UPPER_E_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'G', L'^', UC_UPPER_G_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'H', L'^', UC_UPPER_H_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'I', L'^', UC_UPPER_I_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'J', L'^', UC_UPPER_J_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'O', L'^', UC_UPPER_O_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'S', L'^', UC_UPPER_S_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'U', L'^', UC_UPPER_U_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'W', L'^', UC_UPPER_W_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'Y', L'^', UC_UPPER_Y_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'Z', L'^', 0x1e90, 0x0000),
    DEADTRANS(L'a', L'^', UC_LOWER_A_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'c', L'^', UC_LOWER_C_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'e', L'^', UC_LOWER_E_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'g', L'^', UC_LOWER_G_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'h', L'^', UC_LOWER_H_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'i', L'^', UC_LOWER_I_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'j', L'^', UC_LOWER_J_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'o', L'^', UC_LOWER_O_CIRCUMFLEX, 0x0000),
    DEADTRANS(L's', L'^', UC_LOWER_S_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'u', L'^', UC_LOWER_U_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'w', L'^', UC_LOWER_W_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'x', L'^', 0x02e3, 0x0000),
    DEADTRANS(L'y', L'^', UC_LOWER_Y_CIRCUMFLEX, 0x0000),
    DEADTRANS(L'z', L'^', 0x1e91, 0x0000),
    DEADTRANS(UC_UPPER_A_GRAVE, L'^', 0x1ea6, 0x0000),
    DEADTRANS(UC_UPPER_E_GRAVE, L'^', 0x1ec0, 0x0000),
    DEADTRANS(UC_UPPER_E_ACUTE, L'^', 0x1ebe, 0x0000),
    DEADTRANS(UC_LOWER_A_GRAVE, L'^', 0x1ea7, 0x0000),
    DEADTRANS(UC_LOWER_E_GRAVE, L'^', 0x1ec1, 0x0000),
    DEADTRANS(UC_LOWER_E_ACUTE, L'^', 0x1ebf, 0x0000),
    DEADTRANS(UC_MINUS, L'^', 0x207b, 0x0000),
    DEADTRANS(UC_CURRENCY, L'^', UC_COMB_CIRCUMFLEX, 0x0000),
    DEADTRANS(UC_MICRO, L'^', UC_COMB_CIRCUMFLEX, 0x0000),
    DEADTRANS(0x017f, L'^', UC_COMB_CIRCUMFLEX, 0x0000),
    DEADTRANS(UC_NBSP, L'^', L'^', 0x0000),
    DEADTRANS(UC_NNBSP, L'^', L'^', 0x0000),
    DEADTRANS(L' ', L'^', L'^', 0x0000),
    DEADTRANS(L'A', L'`', UC_UPPER_A_GRAVE, 0x0000),
    DEADTRANS(L'E', L'`', UC_UPPER_E_GRAVE, 0x0000),
    DEADTRANS(L'I', L'`', UC_UPPER_I_GRAVE, 0x0000),
    DEADTRANS(L'N', L'`', 0x01f8, 0x0000),
    DEADTRANS(L'O', L'`', UC_UPPER_O_GRAVE, 0x0000),
    DEADTRANS(L'U', L'`', UC_UPPER_U_GRAVE, 0x0000),
    DEADTRANS(L'W', L'`', UC_UPPER_W_GRAVE, 0x0000),
    DEADTRANS(L'Y', L'`', UC_UPPER_Y_GRAVE, 0x0000),
    DEADTRANS(L'a', L'`', UC_LOWER_A_GRAVE, 0x0000),
    DEADTRANS(L'e', L'`', UC_LOWER_E_GRAVE, 0x0000),
    DEADTRANS(L'i', L'`', UC_LOWER_I_GRAVE, 0x0000),
    DEADTRANS(L'n', L'`', 0x01f9, 0x0000),
    DEADTRANS(L'o', L'`', UC_LOWER_O_GRAVE, 0x0000),
    DEADTRANS(L'u', L'`', UC_LOWER_U_GRAVE, 0x0000),
    DEADTRANS(L'w', L'`', UC_LOWER_W_GRAVE, 0x0000),
    DEADTRANS(L'y', L'`', UC_LOWER_Y_GRAVE, 0x0000),
    DEADTRANS(UC_UPPER_E_CIRCUMFLEX, L'`', 0x1ec0, 0x0000),
    DEADTRANS(UC_LOWER_E_CIRCUMFLEX, L'`', 0x1ec1, 0x0000),
    DEADTRANS(UC_CURRENCY, L'`', UC_COMB_GRAVE, 0x0000),
    DEADTRANS(UC_MICRO, L'`', UC_COMB_GRAVE, 0x0000),
    DEADTRANS(0x017f, L'`', UC_COMB_GRAVE, 0x0000),
    DEADTRANS(UC_NBSP, L'`', L'`', 0x0000),
    DEADTRANS(UC_NNBSP, L'`', L'`', 0x0000),
    DEADTRANS(L' ', L'`', L'`', 0x0000),
    DEADTRANS(L'-', L'~', 0x2243, 0x0000),
    DEADTRANS(L'<', L'~', 0x2272, 0x0000),
    DEADTRANS(L'=', L'~', UC_ALMOST_EQUAL, 0x0000),
    DEADTRANS(L'>', L'~', 0x2273, 0x0000),
    DEADTRANS(L'A', L'~', UC_UPPER_A_TILDE, 0x0000),
    DEADTRANS(L'E', L'~', 0x1ebc, 0x0000),
    DEADTRANS(L'I', L'~', UC_UPPER_I_TILDE, 0x0000),
    DEADTRANS(L'N', L'~', UC_UPPER_N_TILDE, 0x0000),
    DEADTRANS(L'O', L'~', UC_UPPER_O_TILDE, 0x0000),
    DEADTRANS(L'U', L'~', UC_UPPER_U_TILDE, 0x0000),
    DEADTRANS(L'V', L'~', 0x1e7c, 0x0000),
    DEADTRANS(L'Y', L'~', 0x1ef8, 0x0000),
    DEADTRANS(L'a', L'~', UC_LOWER_A_TILDE, 0x0000),
    DEADTRANS(L'e', L'~', 0x1ebd, 0x0000),
    DEADTRANS(L'i', L'~', UC_LOWER_I_TILDE, 0x0000),
    DEADTRANS(L'n', L'~', UC_LOWER_N_TILDE, 0x0000),
    DEADTRANS(L'o', L'~', UC_LOWER_O_TILDE, 0x0000),
    DEADTRANS(L'u', L'~', UC_LOWER_U_TILDE, 0x0000),
    DEADTRANS(L'v', L'~', 0x1e7d, 0x0000),
    DEADTRANS(L'y', L'~', 0x1ef9, 0x0000),
    DEADTRANS(UC_UPPER_E_CIRCUMFLEX, L'~', 0x1ec4, 0x0000),
    DEADTRANS(UC_LOWER_E_CIRCUMFLEX, L'~', 0x1ec5, 0x0000),
    DEADTRANS(UC_CURRENCY, L'~', UC_COMB_TILDE, 0x0000),
    DEADTRANS(UC_MICRO, L'~', UC_COMB_TILDE, 0x0000),
    DEADTRANS(0x017f, L'~', UC_COMB_TILDE, 0x0000),
    DEADTRANS(UC_NBSP, L'~', L'~', 0x0000),
    DEADTRANS(UC_NNBSP, L'~', L'~', 0x0000),
    DEADTRANS(L' ', L'~', L'~', 0x0000),
    DEADTRANS(L'%', UC_CURRENCY, 0x20b0, 0x0000),
    DEADTRANS(L'A', UC_CURRENCY, 0x20b3, 0x0000),
    DEADTRANS(L'B', UC_CURRENCY, 0x0e3f, 0x0000),
    DEADTRANS(L'C', UC_CURRENCY, 0x20b5, 0x0000),
    DEADTRANS(L'D', UC_CURRENCY, UC_DRACHMA, 0x0000),
    DEADTRANS(L'F', UC_CURRENCY, 0x20a3, 0x0000),
    DEADTRANS(L'L', UC_CURRENCY, 0x20a4, 0x0000),
    DEADTRANS(L'M', UC_CURRENCY, 0x2133, 0x0000),
    DEADTRANS(L'P', UC_CURRENCY, 0x20a7, 0x0000),
    DEADTRANS(L'R', UC_CURRENCY, 0x20b9, 0x0000),
    DEADTRANS(L'S', UC_CURRENCY, 0x20b7, 0x0000),
    DEADTRANS(L'T', UC_CURRENCY, 0x20ae, 0x0000),
    DEADTRANS(L'b', UC_CURRENCY, 0x20bf, 0x0000),
    DEADTRANS(L'c', UC_CURRENCY, UC_CENT, 0x0000),
    DEADTRANS(L'd', UC_CURRENCY, 0x20ab, 0x0000),
    DEADTRANS(L'e', UC_CURRENCY, 0x20a0, 0x0000),
    DEADTRANS(L'f', UC_CURRENCY, UC_LATIN_SMALL_F_HOOK, 0x0000),
    DEADTRANS(L'g', UC_CURRENCY, 0x20b2, 0x0000),
    DEADTRANS(L'h', UC_CURRENCY, 0x20b4, 0x0000),
    DEADTRANS(L'k', UC_CURRENCY, 0x20ad, 0x0000),
    DEADTRANS(L'l', UC_CURRENCY, 0x20ba, 0x0000),
    DEADTRANS(L'm', UC_CURRENCY, 0x20a5, 0x0000),
    DEADTRANS(L'n', UC_CURRENCY, 0x20a6, 0x0000),
    DEADTRANS(L'p', UC_CURRENCY, 0x20b1, 0x0000),
    DEADTRANS(L'r', UC_CURRENCY, 0x20bd, 0x0000),
    DEADTRANS(L's', UC_CURRENCY, 0x20aa, 0x0000),
    DEADTRANS(L't', UC_CURRENCY, 0x20b8, 0x0000),
    DEADTRANS(L'w', UC_CURRENCY, 0x20a9, 0x0000),
    DEADTRANS(L'y', UC_CURRENCY, UC_YEN, 0x0000),
    DEADTRANS(L'|', UC_CURRENCY, 0x20be, 0x0000),
    DEADTRANS(UC_REGISTERED, UC_CURRENCY, 0x20a8, 0x0000),
    DEADTRANS(UC_UPPER_C_CEDILLA, UC_CURRENCY, 0x20a1, 0x0000),
    DEADTRANS(UC_LOWER_C_CEDILLA, UC_CURRENCY, 0x20a2, 0x0000),
    DEADTRANS(UC_INFINITY, UC_CURRENCY, 0x20bc, 0x0000),
    DEADTRANS(UC_MICRO, UC_CURRENCY, UC_CURRENCY, 0x0000),
    DEADTRANS(0x017f, UC_CURRENCY, UC_CURRENCY, 0x0000),
    DEADTRANS(UC_NBSP, UC_CURRENCY, UC_CURRENCY, 0x0000),
    DEADTRANS(UC_NNBSP, UC_CURRENCY, UC_CURRENCY, 0x0000),
    DEADTRANS(L' ', UC_CURRENCY, UC_CURRENCY, 0x0000),
    DEADTRANS(L'A', UC_DIAERESIS, UC_UPPER_A_DIAERESIS, 0x0000),
    DEADTRANS(L'E', UC_DIAERESIS, UC_UPPER_E_DIAERESIS, 0x0000),
    DEADTRANS(L'H', UC_DIAERESIS, 0x1e26, 0x0000),
    DEADTRANS(L'I', UC_DIAERESIS, UC_UPPER_I_DIAERESIS, 0x0000),
    DEADTRANS(L'O', UC_DIAERESIS, UC_UPPER_O_DIAERESIS, 0x0000),
    DEADTRANS(L'U', UC_DIAERESIS, UC_UPPER_U_DIAERESIS, 0x0000),
    DEADTRANS(L'W', UC_DIAERESIS, UC_UPPER_W_DIAERESIS, 0x0000),
    DEADTRANS(L'X', UC_DIAERESIS, 0x1e8c, 0x0000),
    DEADTRANS(L'Y', UC_DIAERESIS, UC_UPPER_Y_DIAERESIS, 0x0000),
    DEADTRANS(L'a', UC_DIAERESIS, UC_LOWER_A_DIAERESIS, 0x0000),
    DEADTRANS(L'e', UC_DIAERESIS, UC_LOWER_E_DIAERESIS, 0x0000),
    DEADTRANS(L'h', UC_DIAERESIS, 0x1e27, 0x0000),
    DEADTRANS(L'i', UC_DIAERESIS, UC_LOWER_I_DIAERESIS, 0x0000),
    DEADTRANS(L'o', UC_DIAERESIS, UC_LOWER_O_DIAERESIS, 0x0000),
    DEADTRANS(L't', UC_DIAERESIS, 0x1e97, 0x0000),
    DEADTRANS(L'u', UC_DIAERESIS, UC_LOWER_U_DIAERESIS, 0x0000),
    DEADTRANS(L'w', UC_DIAERESIS, UC_LOWER_W_DIAERESIS, 0x0000),
    DEADTRANS(L'x', UC_DIAERESIS, 0x1e8d, 0x0000),
    DEADTRANS(L'y', UC_DIAERESIS, UC_LOWER_Y_DIAERESIS, 0x0000),
    DEADTRANS(UC_UPPER_U_GRAVE, UC_DIAERESIS, 0x01db, 0x0000),
    DEADTRANS(UC_LOWER_U_GRAVE, UC_DIAERESIS, 0x01dc, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_DIAERESIS, UC_COMB_DIAERESIS, 0x0000),
    DEADTRANS(UC_MICRO, UC_DIAERESIS, UC_COMB_DIAERESIS, 0x0000),
    DEADTRANS(0x017f, UC_DIAERESIS, UC_COMB_DIAERESIS, 0x0000),
    DEADTRANS(UC_NBSP, UC_DIAERESIS, UC_DIAERESIS, 0x0000),
    DEADTRANS(UC_NNBSP, UC_DIAERESIS, UC_DIAERESIS, 0x0000),
    DEADTRANS(L' ', UC_DIAERESIS, UC_DIAERESIS, 0x0000),
    DEADTRANS(L'A', UC_MACRON, UC_UPPER_A_MACRON, 0x0000),
    DEADTRANS(L'E', UC_MACRON, UC_UPPER_E_MACRON, 0x0000),
    DEADTRANS(L'G', UC_MACRON, 0x1e20, 0x0000),
    DEADTRANS(L'I', UC_MACRON, UC_UPPER_I_MACRON, 0x0000),
    DEADTRANS(L'O', UC_MACRON, UC_UPPER_O_MACRON, 0x0000),
    DEADTRANS(L'U', UC_MACRON, UC_UPPER_U_MACRON, 0x0000),
    DEADTRANS(L'Y', UC_MACRON, 0x0232, 0x0000),
    DEADTRANS(L'a', UC_MACRON, UC_LOWER_A_MACRON, 0x0000),
    DEADTRANS(L'e', UC_MACRON, UC_LOWER_E_MACRON, 0x0000),
    DEADTRANS(L'g', UC_MACRON, 0x1e21, 0x0000),
    DEADTRANS(L'i', UC_MACRON, UC_LOWER_I_MACRON, 0x0000),
    DEADTRANS(L'o', UC_MACRON, UC_LOWER_O_MACRON, 0x0000),
    DEADTRANS(L'u', UC_MACRON, UC_LOWER_U_MACRON, 0x0000),
    DEADTRANS(L'y', UC_MACRON, 0x0233, 0x0000),
    DEADTRANS(UC_UPPER_AE, UC_MACRON, 0x01e2, 0x0000),
    DEADTRANS(UC_UPPER_E_GRAVE, UC_MACRON, 0x1e14, 0x0000),
    DEADTRANS(UC_UPPER_E_ACUTE, UC_MACRON, 0x1e16, 0x0000),
    DEADTRANS(UC_LOWER_AE, UC_MACRON, 0x01e3, 0x0000),
    DEADTRANS(UC_LOWER_E_GRAVE, UC_MACRON, 0x1e15, 0x0000),
    DEADTRANS(UC_LOWER_E_ACUTE, UC_MACRON, 0x1e17, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_MACRON, UC_COMB_MACRON, 0x0000),
    DEADTRANS(UC_MICRO, UC_MACRON, UC_COMB_MACRON, 0x0000),
    DEADTRANS(0x017f, UC_MACRON, UC_COMB_MACRON, 0x0000),
    DEADTRANS(UC_NBSP, UC_MACRON, UC_MACRON, 0x0000),
    DEADTRANS(UC_NNBSP, UC_MACRON, UC_MACRON, 0x0000),
    DEADTRANS(L' ', UC_MACRON, UC_MACRON, 0x0000),
    DEADTRANS(L'A', UC_COMB_INV_BREVE, 0x0202, 0x0000),
    DEADTRANS(L'E', UC_COMB_INV_BREVE, 0x0206, 0x0000),
    DEADTRANS(L'I', UC_COMB_INV_BREVE, 0x020a, 0x0000),
    DEADTRANS(L'O', UC_COMB_INV_BREVE, 0x020e, 0x0000),
    DEADTRANS(L'R', UC_COMB_INV_BREVE, 0x0212, 0x0000),
    DEADTRANS(L'U', UC_COMB_INV_BREVE, 0x0216, 0x0000),
    DEADTRANS(L'a', UC_COMB_INV_BREVE, 0x0203, 0x0000),
    DEADTRANS(L'e', UC_COMB_INV_BREVE, 0x0207, 0x0000),
    DEADTRANS(L'i', UC_COMB_INV_BREVE, 0x020b, 0x0000),
    DEADTRANS(L'o', UC_COMB_INV_BREVE, 0x020f, 0x0000),
    DEADTRANS(L'r', UC_COMB_INV_BREVE, 0x0213, 0x0000),
    DEADTRANS(L'u', UC_COMB_INV_BREVE, 0x0217, 0x0000),
    DEADTRANS(UC_UPPER_A_GRAVE, UC_COMB_INV_BREVE, 0x1ea6, 0x0000),
    DEADTRANS(UC_UPPER_E_GRAVE, UC_COMB_INV_BREVE, 0x1ec0, 0x0000),
    DEADTRANS(UC_LOWER_A_GRAVE, UC_COMB_INV_BREVE, 0x1ea7, 0x0000),
    DEADTRANS(UC_LOWER_E_GRAVE, UC_COMB_INV_BREVE, 0x1ec1, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_COMB_INV_BREVE, UC_COMB_INV_BREVE, 0x0000),
    DEADTRANS(UC_MICRO, UC_COMB_INV_BREVE, UC_COMB_INV_BREVE, 0x0000),
    DEADTRANS(0x017f, UC_COMB_INV_BREVE, UC_COMB_INV_BREVE, 0x0000),
    DEADTRANS(UC_NBSP, UC_COMB_INV_BREVE, UC_COMB_INV_BREVE, 0x0000),
    DEADTRANS(UC_NNBSP, UC_COMB_INV_BREVE, UC_COMB_INV_BREVE, 0x0000),
    DEADTRANS(L' ', UC_COMB_INV_BREVE, UC_COMB_INV_BREVE, 0x0000),
    DEADTRANS(L'A', UC_ACUTE, UC_UPPER_A_ACUTE, 0x0000),
    DEADTRANS(L'C', UC_ACUTE, UC_UPPER_C_ACUTE, 0x0000),
    DEADTRANS(L'E', UC_ACUTE, UC_UPPER_E_ACUTE, 0x0000),
    DEADTRANS(L'G', UC_ACUTE, 0x01f4, 0x0000),
    DEADTRANS(L'I', UC_ACUTE, UC_UPPER_I_ACUTE, 0x0000),
    DEADTRANS(L'K', UC_ACUTE, 0x1e30, 0x0000),
    DEADTRANS(L'L', UC_ACUTE, UC_UPPER_L_ACUTE, 0x0000),
    DEADTRANS(L'M', UC_ACUTE, 0x1e3e, 0x0000),
    DEADTRANS(L'N', UC_ACUTE, UC_UPPER_N_ACUTE, 0x0000),
    DEADTRANS(L'O', UC_ACUTE, UC_UPPER_O_ACUTE, 0x0000),
    DEADTRANS(L'P', UC_ACUTE, 0x1e54, 0x0000),
    DEADTRANS(L'R', UC_ACUTE, UC_UPPER_R_ACUTE, 0x0000),
    DEADTRANS(L'S', UC_ACUTE, UC_UPPER_S_ACUTE, 0x0000),
    DEADTRANS(L'U', UC_ACUTE, UC_UPPER_U_ACUTE, 0x0000),
    DEADTRANS(L'W', UC_ACUTE, UC_UPPER_W_ACUTE, 0x0000),
    DEADTRANS(L'Y', UC_ACUTE, UC_UPPER_Y_ACUTE, 0x0000),
    DEADTRANS(L'Z', UC_ACUTE, UC_UPPER_Z_ACUTE, 0x0000),
    DEADTRANS(L'a', UC_ACUTE, UC_LOWER_A_ACUTE, 0x0000),
    DEADTRANS(L'c', UC_ACUTE, UC_LOWER_C_ACUTE, 0x0000),
    DEADTRANS(L'e', UC_ACUTE, UC_LOWER_E_ACUTE, 0x0000),
    DEADTRANS(L'g', UC_ACUTE, 0x01f5, 0x0000),
    DEADTRANS(L'i', UC_ACUTE, UC_LOWER_I_ACUTE, 0x0000),
    DEADTRANS(L'k', UC_ACUTE, 0x1e31, 0x0000),
    DEADTRANS(L'l', UC_ACUTE, UC_LOWER_L_ACUTE, 0x0000),
    DEADTRANS(L'm', UC_ACUTE, 0x1e3f, 0x0000),
    DEADTRANS(L'n', UC_ACUTE, UC_LOWER_N_ACUTE, 0x0000),
    DEADTRANS(L'o', UC_ACUTE, UC_LOWER_O_ACUTE, 0x0000),
    DEADTRANS(L'p', UC_ACUTE, 0x1e55, 0x0000),
    DEADTRANS(L'r', UC_ACUTE, UC_LOWER_R_ACUTE, 0x0000),
    DEADTRANS(L's', UC_ACUTE, UC_LOWER_S_ACUTE, 0x0000),
    DEADTRANS(L'u', UC_ACUTE, UC_LOWER_U_ACUTE, 0x0000),
    DEADTRANS(L'w', UC_ACUTE, UC_LOWER_W_ACUTE, 0x0000),
    DEADTRANS(L'y', UC_ACUTE, UC_LOWER_Y_ACUTE, 0x0000),
    DEADTRANS(L'z', UC_ACUTE, UC_LOWER_Z_ACUTE, 0x0000),
    DEADTRANS(UC_UPPER_AE, UC_ACUTE, 0x01fc, 0x0000),
    DEADTRANS(UC_UPPER_C_CEDILLA, UC_ACUTE, 0x1e08, 0x0000),
    DEADTRANS(UC_UPPER_E_CIRCUMFLEX, UC_ACUTE, 0x1ebe, 0x0000),
    DEADTRANS(UC_LOWER_AE, UC_ACUTE, 0x01fd, 0x0000),
    DEADTRANS(UC_LOWER_C_CEDILLA, UC_ACUTE, 0x1e09, 0x0000),
    DEADTRANS(UC_LOWER_E_CIRCUMFLEX, UC_ACUTE, 0x1ebf, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_ACUTE, UC_COMB_ACUTE, 0x0000),
    DEADTRANS(UC_MICRO, UC_ACUTE, UC_COMB_ACUTE, 0x0000),
    DEADTRANS(0x017f, UC_ACUTE, UC_COMB_ACUTE, 0x0000),
    DEADTRANS(UC_NBSP, UC_ACUTE, UC_ACUTE, 0x0000),
    DEADTRANS(UC_NNBSP, UC_ACUTE, UC_ACUTE, 0x0000),
    DEADTRANS(L' ', UC_ACUTE, UC_ACUTE, 0x0000),
    DEADTRANS(L'A', UC_MICRO, UC_UPPER_ALPHA, 0x0000),
    DEADTRANS(L'B', UC_MICRO, UC_UPPER_BETA, 0x0000),
    DEADTRANS(L'C', UC_MICRO, UC_UPPER_PSI, 0x0000),
    DEADTRANS(L'D', UC_MICRO, UC_UPPER_DELTA, 0x0000),
    DEADTRANS(L'E', UC_MICRO, UC_UPPER_EPSILON, 0x0000),
    DEADTRANS(L'F', UC_MICRO, UC_UPPER_PHI, 0x0000),
    DEADTRANS(L'G', UC_MICRO, UC_UPPER_GAMMA, 0x0000),
    DEADTRANS(L'H', UC_MICRO, UC_UPPER_ETA, 0x0000),
    DEADTRANS(L'I', UC_MICRO, UC_UPPER_IOTA, 0x0000),
    DEADTRANS(L'J', UC_MICRO, UC_UPPER_XI, 0x0000),
    DEADTRANS(L'K', UC_MICRO, UC_UPPER_KAPPA, 0x0000),
    DEADTRANS(L'L', UC_MICRO, UC_UPPER_LAMDA, 0x0000),
    DEADTRANS(L'M', UC_MICRO, UC_UPPER_MU, 0x0000),
    DEADTRANS(L'N', UC_MICRO, UC_UPPER_NU, 0x0000),
    DEADTRANS(L'O', UC_MICRO, UC_UPPER_OMICRON, 0x0000),
    DEADTRANS(L'P', UC_MICRO, UC_UPPER_PI, 0x0000),
    DEADTRANS(L'R', UC_MICRO, UC_UPPER_RHO, 0x0000),
    DEADTRANS(L'S', UC_MICRO, UC_UPPER_SIGMA, 0x0000),
    DEADTRANS(L'T', UC_MICRO, UC_UPPER_TAU, 0x0000),
    DEADTRANS(L'U', UC_MICRO, UC_UPPER_THETA, 0x0000),
    DEADTRANS(L'V', UC_MICRO, UC_UPPER_OMEGA, 0x0000),
    DEADTRANS(L'X', UC_MICRO, UC_UPPER_CHI, 0x0000),
    DEADTRANS(L'Y', UC_MICRO, UC_UPPER_UPSILON, 0x0000),
    DEADTRANS(L'Z', UC_MICRO, UC_UPPER_ZETA, 0x0000),
    DEADTRANS(L'a', UC_MICRO, UC_LOWER_ALPHA, 0x0000),
    DEADTRANS(L'b', UC_MICRO, UC_LOWER_BETA, 0x0000),
    DEADTRANS(L'c', UC_MICRO, UC_LOWER_PSI, 0x0000),
    DEADTRANS(L'd', UC_MICRO, UC_LOWER_DELTA, 0x0000),
    DEADTRANS(L'e', UC_MICRO, UC_LOWER_EPSILON, 0x0000),
    DEADTRANS(L'f', UC_MICRO, UC_LOWER_PHI, 0x0000),
    DEADTRANS(L'g', UC_MICRO, UC_LOWER_GAMMA, 0x0000),
    DEADTRANS(L'h', UC_MICRO, UC_LOWER_ETA, 0x0000),
    DEADTRANS(L'i', UC_MICRO, UC_LOWER_IOTA, 0x0000),
    DEADTRANS(L'j', UC_MICRO, UC_LOWER_XI, 0x0000),
    DEADTRANS(L'k', UC_MICRO, UC_LOWER_KAPPA, 0x0000),
    DEADTRANS(L'l', UC_MICRO, UC_LOWER_LAMDA, 0x0000),
    DEADTRANS(L'm', UC_MICRO, UC_LOWER_MU, 0x0000),
    DEADTRANS(L'n', UC_MICRO, UC_LOWER_NU, 0x0000),
    DEADTRANS(L'o', UC_MICRO, UC_LOWER_OMICRON, 0x0000),
    DEADTRANS(L'p', UC_MICRO, UC_LOWER_PI, 0x0000),
    DEADTRANS(L'r', UC_MICRO, UC_LOWER_RHO, 0x0000),
    DEADTRANS(L's', UC_MICRO, UC_LOWER_SIGMA, 0x0000),
    DEADTRANS(L't', UC_MICRO, UC_LOWER_TAU, 0x0000),
    DEADTRANS(L'u', UC_MICRO, UC_LOWER_THETA, 0x0000),
    DEADTRANS(L'v', UC_MICRO, UC_LOWER_OMEGA, 0x0000),
    DEADTRANS(L'w', UC_MICRO, UC_LOWER_FINAL_SIGMA, 0x0000),
    DEADTRANS(L'x', UC_MICRO, UC_LOWER_CHI, 0x0000),
    DEADTRANS(L'y', UC_MICRO, UC_LOWER_UPSILON, 0x0000),
    DEADTRANS(L'z', UC_MICRO, UC_LOWER_ZETA, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_MICRO, UC_MICRO, 0x0000),
    DEADTRANS(0x017f, UC_MICRO, UC_MICRO, 0x0000),
    DEADTRANS(UC_NBSP, UC_MICRO, UC_MICRO, 0x0000),
    DEADTRANS(UC_NNBSP, UC_MICRO, UC_MICRO, 0x0000),
    DEADTRANS(L' ', UC_MICRO, UC_MICRO, 0x0000),
    DEADTRANS(L'C', UC_CEDILLA, UC_UPPER_C_CEDILLA, 0x0000),
    DEADTRANS(L'D', UC_CEDILLA, 0x1e10, 0x0000),
    DEADTRANS(L'E', UC_CEDILLA, 0x0228, 0x0000),
    DEADTRANS(L'G', UC_CEDILLA, UC_UPPER_G_CEDILLA, 0x0000),
    DEADTRANS(L'H', UC_CEDILLA, 0x1e28, 0x0000),
    DEADTRANS(L'K', UC_CEDILLA, UC_UPPER_K_CEDILLA, 0x0000),
    DEADTRANS(L'L', UC_CEDILLA, UC_UPPER_L_CEDILLA, 0x0000),
    DEADTRANS(L'N', UC_CEDILLA, UC_UPPER_N_CEDILLA, 0x0000),
    DEADTRANS(L'R', UC_CEDILLA, UC_UPPER_R_CEDILLA, 0x0000),
    DEADTRANS(L'S', UC_CEDILLA, UC_UPPER_S_CEDILLA, 0x0000),
    DEADTRANS(L'T', UC_CEDILLA, UC_UPPER_T_CEDILLA, 0x0000),
    DEADTRANS(L'c', UC_CEDILLA, UC_LOWER_C_CEDILLA, 0x0000),
    DEADTRANS(L'd', UC_CEDILLA, 0x1e11, 0x0000),
    DEADTRANS(L'e', UC_CEDILLA, 0x0229, 0x0000),
    DEADTRANS(L'g', UC_CEDILLA, UC_LOWER_G_CEDILLA, 0x0000),
    DEADTRANS(L'h', UC_CEDILLA, 0x1e29, 0x0000),
    DEADTRANS(L'k', UC_CEDILLA, UC_LOWER_K_CEDILLA, 0x0000),
    DEADTRANS(L'l', UC_CEDILLA, UC_LOWER_L_CEDILLA, 0x0000),
    DEADTRANS(L'n', UC_CEDILLA, UC_LOWER_N_CEDILLA, 0x0000),
    DEADTRANS(L'r', UC_CEDILLA, UC_LOWER_R_CEDILLA, 0x0000),
    DEADTRANS(L's', UC_CEDILLA, UC_LOWER_S_CEDILLA, 0x0000),
    DEADTRANS(L't', UC_CEDILLA, UC_LOWER_T_CEDILLA, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_CEDILLA, UC_COMB_CEDILLA, 0x0000),
    DEADTRANS(UC_MICRO, UC_CEDILLA, UC_COMB_CEDILLA, 0x0000),
    DEADTRANS(0x017f, UC_CEDILLA, UC_COMB_CEDILLA, 0x0000),
    DEADTRANS(UC_NBSP, UC_CEDILLA, UC_CEDILLA, 0x0000),
    DEADTRANS(UC_NNBSP, UC_CEDILLA, UC_CEDILLA, 0x0000),
    DEADTRANS(L' ', UC_CEDILLA, UC_CEDILLA, 0x0000),
    DEADTRANS(L'\'', 0x017f, 0x02bc, 0x0000),
    DEADTRANS(L'0', 0x017f, UC_DA_LEFT_QUOT, 0x0000),
    DEADTRANS(L'7', 0x017f, UC_SA_RIGHT_QUOT, 0x0000),
    DEADTRANS(L'8', 0x017f, UC_SA_LEFT_QUOT, 0x0000),
    DEADTRANS(L'9', 0x017f, UC_DA_RIGHT_QUOT, 0x0000),
    DEADTRANS(L'<', 0x017f, UC_LESS_EQUAL, 0x0000),
    DEADTRANS(L'>', 0x017f, UC_GREATER_EQUAL, 0x0000),
    DEADTRANS(L'D', 0x017f, UC_UPPER_ETH, 0x0000),
    DEADTRANS(L'E', 0x017f, 0x018f, 0x0000),
    DEADTRANS(L'G', 0x017f, UC_UPPER_ENG, 0x0000),
    DEADTRANS(L'I', 0x017f, UC_UPPER_I_DOT_ABOVE, 0x0000),
    DEADTRANS(L'J', 0x017f, 0x0132, 0x0000),
    DEADTRANS(L'T', 0x017f, UC_UPPER_THORN, 0x0000),
    DEADTRANS(L'a', 0x017f, UC_FORDINAL, 0x0000),
    DEADTRANS(L'd', 0x017f, UC_LOWER_ETH, 0x0000),
    DEADTRANS(L'e', 0x017f, 0x0259, 0x0000),
    DEADTRANS(L'g', 0x017f, UC_LOWER_ENG, 0x0000),
    DEADTRANS(L'i', 0x017f, UC_LOWER_DOTLESS_I, 0x0000),
    DEADTRANS(L'j', 0x017f, 0x0133, 0x0000),
    DEADTRANS(L'o', 0x017f, UC_MORDINAL, 0x0000),
    DEADTRANS(L's', 0x017f, 0x017f, 0x0000),
    DEADTRANS(L't', 0x017f, UC_LOWER_THORN, 0x0000),
    DEADTRANS(UC_NBSP, 0x017f, UC_EM_SPACE, 0x0000),
    DEADTRANS(UC_DA_LEFT_QUOT, 0x017f, UC_D9_QUOT, 0x0000),
    DEADTRANS(UC_DA_RIGHT_QUOT, 0x017f, 0x201f, 0x0000),
    DEADTRANS(0x017f, 0x017f, UC_NULL, 0x0000),
    DEADTRANS(UC_S_LEFT_QUOT, 0x017f, UC_S9_QUOT, 0x0000),
    DEADTRANS(UC_S_RIGHT_QUOT, 0x017f, 0x201b, 0x0000),
    DEADTRANS(UC_NNBSP, 0x017f, UC_EN_SPACE, 0x0000),
    DEADTRANS(UC_CURRENCY, 0x017f, UC_NULL, 0x0000),
    DEADTRANS(UC_MICRO, 0x017f, UC_NULL, 0x0000),
    DEADTRANS(UC_NBSP, 0x017f, UC_NULL, 0x0000),
    DEADTRANS(UC_NNBSP, 0x017f, UC_NULL, 0x0000),
    DEADTRANS(L' ', 0x017f, UC_NULL, 0x0000),
    DEADTRANS(L'(', UC_CARON, 0x208d, 0x0000),
    DEADTRANS(L')', UC_CARON, 0x208e, 0x0000),
    DEADTRANS(L'+', UC_CARON, 0x208a, 0x0000),
    DEADTRANS(L'-', UC_CARON, 0x208b, 0x0000),
    DEADTRANS(L'0', UC_CARON, 0x2080, 0x0000),
    DEADTRANS(L'1', UC_CARON, 0x2081, 0x0000),
    DEADTRANS(L'2', UC_CARON, 0x2082, 0x0000),
    DEADTRANS(L'3', UC_CARON, 0x2083, 0x0000),
    DEADTRANS(L'4', UC_CARON, 0x2084, 0x0000),
    DEADTRANS(L'5', UC_CARON, 0x2085, 0x0000),
    DEADTRANS(L'6', UC_CARON, 0x2086, 0x0000),
    DEADTRANS(L'7', UC_CARON, 0x2087, 0x0000),
    DEADTRANS(L'8', UC_CARON, 0x2088, 0x0000),
    DEADTRANS(L'9', UC_CARON, 0x2089, 0x0000),
    DEADTRANS(L'=', UC_CARON, 0x208c, 0x0000),
    DEADTRANS(L'A', UC_CARON, 0x01cd, 0x0000),
    DEADTRANS(L'C', UC_CARON, UC_UPPER_C_CARON, 0x0000),
    DEADTRANS(L'D', UC_CARON, UC_UPPER_D_CARON, 0x0000),
    DEADTRANS(L'E', UC_CARON, UC_UPPER_E_CARON, 0x0000),
    DEADTRANS(L'G', UC_CARON, 0x01e6, 0x0000),
    DEADTRANS(L'H', UC_CARON, 0x021e, 0x0000),
    DEADTRANS(L'I', UC_CARON, 0x01cf, 0x0000),
    DEADTRANS(L'K', UC_CARON, 0x01e8, 0x0000),
    DEADTRANS(L'L', UC_CARON, UC_UPPER_L_CARON, 0x0000),
    DEADTRANS(L'N', UC_CARON, UC_UPPER_N_CARON, 0x0000),
    DEADTRANS(L'O', UC_CARON, 0x01d1, 0x0000),
    DEADTRANS(L'R', UC_CARON, UC_UPPER_R_CARON, 0x0000),
    DEADTRANS(L'S', UC_CARON, UC_UPPER_S_CARON, 0x0000),
    DEADTRANS(L'T', UC_CARON, UC_UPPER_T_CARON, 0x0000),
    DEADTRANS(L'U', UC_CARON, 0x01d3, 0x0000),
    DEADTRANS(L'Z', UC_CARON, UC_UPPER_Z_CARON, 0x0000),
    DEADTRANS(L'a', UC_CARON, 0x01ce, 0x0000),
    DEADTRANS(L'c', UC_CARON, UC_LOWER_C_CARON, 0x0000),
    DEADTRANS(L'd', UC_CARON, UC_LOWER_D_CARON, 0x0000),
    DEADTRANS(L'e', UC_CARON, UC_LOWER_E_CARON, 0x0000),
    DEADTRANS(L'g', UC_CARON, 0x01e7, 0x0000),
    DEADTRANS(L'h', UC_CARON, 0x021f, 0x0000),
    DEADTRANS(L'i', UC_CARON, 0x01d0, 0x0000),
    DEADTRANS(L'j', UC_CARON, 0x01f0, 0x0000),
    DEADTRANS(L'k', UC_CARON, 0x01e9, 0x0000),
    DEADTRANS(L'l', UC_CARON, UC_LOWER_L_CARON, 0x0000),
    DEADTRANS(L'n', UC_CARON, UC_LOWER_N_CARON, 0x0000),
    DEADTRANS(L'o', UC_CARON, 0x01d2, 0x0000),
    DEADTRANS(L'r', UC_CARON, UC_LOWER_R_CARON, 0x0000),
    DEADTRANS(L's', UC_CARON, UC_LOWER_S_CARON, 0x0000),
    DEADTRANS(L't', UC_CARON, UC_LOWER_T_CARON, 0x0000),
    DEADTRANS(L'u', UC_CARON, 0x01d4, 0x0000),
    DEADTRANS(L'x', UC_CARON, 0x2093, 0x0000),
    DEADTRANS(L'z', UC_CARON, UC_LOWER_Z_CARON, 0x0000),
    DEADTRANS(0x01b7, UC_CARON, 0x01ee, 0x0000),
    DEADTRANS(0x0292, UC_CARON, 0x01ef, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_CARON, UC_COMB_CARON, 0x0000),
    DEADTRANS(UC_MICRO, UC_CARON, UC_COMB_CARON, 0x0000),
    DEADTRANS(0x017f, UC_CARON, UC_COMB_CARON, 0x0000),
    DEADTRANS(UC_NBSP, UC_CARON, UC_CARON, 0x0000),
    DEADTRANS(UC_NNBSP, UC_CARON, UC_CARON, 0x0000),
    DEADTRANS(L' ', UC_CARON, UC_CARON, 0x0000),
    DEADTRANS(L'B', 0x02cd, 0x1e06, 0x0000),
    DEADTRANS(L'D', 0x02cd, 0x1e0e, 0x0000),
    DEADTRANS(L'K', 0x02cd, 0x1e34, 0x0000),
    DEADTRANS(L'L', 0x02cd, 0x1e3a, 0x0000),
    DEADTRANS(L'N', 0x02cd, 0x1e48, 0x0000),
    DEADTRANS(L'R', 0x02cd, 0x1e5e, 0x0000),
    DEADTRANS(L'T', 0x02cd, 0x1e6e, 0x0000),
    DEADTRANS(L'Z', 0x02cd, 0x1e94, 0x0000),
    DEADTRANS(L'b', 0x02cd, 0x1e07, 0x0000),
    DEADTRANS(L'd', 0x02cd, 0x1e0f, 0x0000),
    DEADTRANS(L'h', 0x02cd, 0x1e96, 0x0000),
    DEADTRANS(L'k', 0x02cd, 0x1e35, 0x0000),
    DEADTRANS(L'l', 0x02cd, 0x1e3b, 0x0000),
    DEADTRANS(L'n', 0x02cd, 0x1e49, 0x0000),
    DEADTRANS(L'r', 0x02cd, 0x1e5f, 0x0000),
    DEADTRANS(L't', 0x02cd, 0x1e6f, 0x0000),
    DEADTRANS(L'z', 0x02cd, 0x1e95, 0x0000),
    DEADTRANS(UC_CURRENCY, 0x02cd, UC_COMB_MACRON_BELOW, 0x0000),
    DEADTRANS(UC_MICRO, 0x02cd, UC_COMB_MACRON_BELOW, 0x0000),
    DEADTRANS(0x017f, 0x02cd, UC_COMB_MACRON_BELOW, 0x0000),
    DEADTRANS(UC_NBSP, 0x02cd, 0x02cd, 0x0000),
    DEADTRANS(UC_NNBSP, 0x02cd, 0x02cd, 0x0000),
    DEADTRANS(L' ', 0x02cd, 0x02cd, 0x0000),
    DEADTRANS(L'A', UC_BREVE, UC_UPPER_A_BREVE, 0x0000),
    DEADTRANS(L'E', UC_BREVE, 0x0114, 0x0000),
    DEADTRANS(L'G', UC_BREVE, UC_UPPER_G_BREVE, 0x0000),
    DEADTRANS(L'I', UC_BREVE, 0x012c, 0x0000),
    DEADTRANS(L'O', UC_BREVE, 0x014e, 0x0000),
    DEADTRANS(L'U', UC_BREVE, UC_UPPER_U_BREVE, 0x0000),
    DEADTRANS(L'a', UC_BREVE, UC_LOWER_A_BREVE, 0x0000),
    DEADTRANS(L'e', UC_BREVE, 0x0115, 0x0000),
    DEADTRANS(L'g', UC_BREVE, UC_LOWER_G_BREVE, 0x0000),
    DEADTRANS(L'i', UC_BREVE, 0x012d, 0x0000),
    DEADTRANS(L'o', UC_BREVE, 0x014f, 0x0000),
    DEADTRANS(L'u', UC_BREVE, UC_LOWER_U_BREVE, 0x0000),
    DEADTRANS(UC_UPPER_A_GRAVE, UC_BREVE, 0x1eb0, 0x0000),
    DEADTRANS(UC_LOWER_A_GRAVE, UC_BREVE, 0x1eb1, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_BREVE, UC_COMB_BREVE, 0x0000),
    DEADTRANS(UC_MICRO, UC_BREVE, UC_COMB_BREVE, 0x0000),
    DEADTRANS(0x017f, UC_BREVE, UC_COMB_BREVE, 0x0000),
    DEADTRANS(UC_NBSP, UC_BREVE, UC_BREVE, 0x0000),
    DEADTRANS(UC_NNBSP, UC_BREVE, UC_BREVE, 0x0000),
    DEADTRANS(L' ', UC_BREVE, UC_BREVE, 0x0000),
    DEADTRANS(L'A', UC_DOT_ABOVE, 0x0226, 0x0000),
    DEADTRANS(L'B', UC_DOT_ABOVE, UC_UPPER_B_DOT_ABOVE, 0x0000),
    DEADTRANS(L'C', UC_DOT_ABOVE, UC_UPPER_C_DOT_ABOVE, 0x0000),
    DEADTRANS(L'D', UC_DOT_ABOVE, UC_UPPER_D_DOT_ABOVE, 0x0000),
    DEADTRANS(L'E', UC_DOT_ABOVE, UC_UPPER_E_DOT_ABOVE, 0x0000),
    DEADTRANS(L'F', UC_DOT_ABOVE, UC_UPPER_F_DOT_ABOVE, 0x0000),
    DEADTRANS(L'G', UC_DOT_ABOVE, UC_UPPER_G_DOT_ABOVE, 0x0000),
    DEADTRANS(L'H', UC_DOT_ABOVE, 0x1e22, 0x0000),
    DEADTRANS(L'I', UC_DOT_ABOVE, UC_UPPER_I_DOT_ABOVE, 0x0000),
    DEADTRANS(L'L', UC_DOT_ABOVE, 0x013f, 0x0000),
    DEADTRANS(L'M', UC_DOT_ABOVE, UC_UPPER_M_DOT_ABOVE, 0x0000),
    DEADTRANS(L'N', UC_DOT_ABOVE, 0x1e44, 0x0000),
    DEADTRANS(L'O', UC_DOT_ABOVE, 0x022e, 0x0000),
    DEADTRANS(L'P', UC_DOT_ABOVE, UC_UPPER_P_DOT_ABOVE, 0x0000),
    DEADTRANS(L'R', UC_DOT_ABOVE, 0x1e58, 0x0000),
    DEADTRANS(L'S', UC_DOT_ABOVE, UC_UPPER_S_DOT_ABOVE, 0x0000),
    DEADTRANS(L'T', UC_DOT_ABOVE, UC_UPPER_T_DOT_ABOVE, 0x0000),
    DEADTRANS(L'W', UC_DOT_ABOVE, 0x1e86, 0x0000),
    DEADTRANS(L'X', UC_DOT_ABOVE, 0x1e8a, 0x0000),
    DEADTRANS(L'Y', UC_DOT_ABOVE, 0x1e8e, 0x0000),
    DEADTRANS(L'Z', UC_DOT_ABOVE, UC_UPPER_Z_DOT_ABOVE, 0x0000),
    DEADTRANS(L'a', UC_DOT_ABOVE, 0x0227, 0x0000),
    DEADTRANS(L'b', UC_DOT_ABOVE, UC_LOWER_B_DOT_ABOVE, 0x0000),
    DEADTRANS(L'c', UC_DOT_ABOVE, UC_LOWER_C_DOT_ABOVE, 0x0000),
    DEADTRANS(L'd', UC_DOT_ABOVE, UC_LOWER_D_DOT_ABOVE, 0x0000),
    DEADTRANS(L'e', UC_DOT_ABOVE, UC_LOWER_E_DOT_ABOVE, 0x0000),
    DEADTRANS(L'f', UC_DOT_ABOVE, UC_LOWER_F_DOT_ABOVE, 0x0000),
    DEADTRANS(L'g', UC_DOT_ABOVE, UC_LOWER_G_DOT_ABOVE, 0x0000),
    DEADTRANS(L'h', UC_DOT_ABOVE, 0x1e23, 0x0000),
    DEADTRANS(L'i', UC_DOT_ABOVE, UC_LOWER_DOTLESS_I, 0x0000),
    DEADTRANS(L'l', UC_DOT_ABOVE, 0x0140, 0x0000),
    DEADTRANS(L'm', UC_DOT_ABOVE, UC_LOWER_M_DOT_ABOVE, 0x0000),
    DEADTRANS(L'n', UC_DOT_ABOVE, 0x1e45, 0x0000),
    DEADTRANS(L'o', UC_DOT_ABOVE, 0x022f, 0x0000),
    DEADTRANS(L'p', UC_DOT_ABOVE, UC_LOWER_P_DOT_ABOVE, 0x0000),
    DEADTRANS(L'r', UC_DOT_ABOVE, 0x1e59, 0x0000),
    DEADTRANS(L's', UC_DOT_ABOVE, UC_LOWER_S_DOT_ABOVE, 0x0000),
    DEADTRANS(L't', UC_DOT_ABOVE, UC_LOWER_T_DOT_ABOVE, 0x0000),
    DEADTRANS(L'w', UC_DOT_ABOVE, 0x1e87, 0x0000),
    DEADTRANS(L'x', UC_DOT_ABOVE, 0x1e8b, 0x0000),
    DEADTRANS(L'y', UC_DOT_ABOVE, 0x1e8f, 0x0000),
    DEADTRANS(L'z', UC_DOT_ABOVE, UC_LOWER_Z_DOT_ABOVE, 0x0000),
    DEADTRANS(0x017f, UC_DOT_ABOVE, 0x1e9b, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_DOT_ABOVE, UC_COMB_DOT_ABOVE, 0x0000),
    DEADTRANS(UC_MICRO, UC_DOT_ABOVE, UC_COMB_DOT_ABOVE, 0x0000),
    DEADTRANS(UC_NBSP, UC_DOT_ABOVE, UC_DOT_ABOVE, 0x0000),
    DEADTRANS(UC_NNBSP, UC_DOT_ABOVE, UC_DOT_ABOVE, 0x0000),
    DEADTRANS(L' ', UC_DOT_ABOVE, UC_DOT_ABOVE, 0x0000),
    DEADTRANS(L'A', 0x02da, UC_UPPER_A_RING_ABOVE, 0x0000),
    DEADTRANS(L'U', 0x02da, UC_UPPER_U_RING_ABOVE, 0x0000),
    DEADTRANS(L'a', 0x02da, UC_LOWER_A_RING_ABOVE, 0x0000),
    DEADTRANS(L'u', 0x02da, UC_LOWER_U_RING_ABOVE, 0x0000),
    DEADTRANS(L'w', 0x02da, 0x1e98, 0x0000),
    DEADTRANS(L'y', 0x02da, 0x1e99, 0x0000),
    DEADTRANS(UC_CURRENCY, 0x02da, UC_COMB_RING_ABOVE, 0x0000),
    DEADTRANS(UC_MICRO, 0x02da, UC_COMB_RING_ABOVE, 0x0000),
    DEADTRANS(0x017f, 0x02da, UC_COMB_RING_ABOVE, 0x0000),
    DEADTRANS(UC_NBSP, 0x02da, 0x02da, 0x0000),
    DEADTRANS(UC_NNBSP, 0x02da, 0x02da, 0x0000),
    DEADTRANS(L' ', 0x02da, 0x02da, 0x0000),
    DEADTRANS(L'A', UC_OGONEK, UC_UPPER_A_OGONEK, 0x0000),
    DEADTRANS(L'E', UC_OGONEK, UC_UPPER_E_OGONEK, 0x0000),
    DEADTRANS(L'I', UC_OGONEK, UC_UPPER_I_OGONEK, 0x0000),
    DEADTRANS(L'O', UC_OGONEK, 0x01ea, 0x0000),
    DEADTRANS(L'U', UC_OGONEK, UC_UPPER_U_OGONEK, 0x0000),
    DEADTRANS(L'a', UC_OGONEK, UC_LOWER_A_OGONEK, 0x0000),
    DEADTRANS(L'e', UC_OGONEK, UC_LOWER_E_OGONEK, 0x0000),
    DEADTRANS(L'i', UC_OGONEK, UC_LOWER_I_OGONEK, 0x0000),
    DEADTRANS(L'o', UC_OGONEK, 0x01eb, 0x0000),
    DEADTRANS(L'u', UC_OGONEK, UC_LOWER_U_OGONEK, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_OGONEK, UC_COMB_OGONEK, 0x0000),
    DEADTRANS(UC_MICRO, UC_OGONEK, UC_COMB_OGONEK, 0x0000),
    DEADTRANS(0x017f, UC_OGONEK, UC_COMB_OGONEK, 0x0000),
    DEADTRANS(UC_NBSP, UC_OGONEK, UC_OGONEK, 0x0000),
    DEADTRANS(UC_NNBSP, UC_OGONEK, UC_OGONEK, 0x0000),
    DEADTRANS(L' ', UC_OGONEK, UC_OGONEK, 0x0000),
    DEADTRANS(L'O', UC_DOUBLE_ACUTE, UC_UPPER_O_DACUTE, 0x0000),
    DEADTRANS(L'U', UC_DOUBLE_ACUTE, UC_UPPER_U_DACUTE, 0x0000),
    DEADTRANS(L'o', UC_DOUBLE_ACUTE, UC_LOWER_O_DACUTE, 0x0000),
    DEADTRANS(L'u', UC_DOUBLE_ACUTE, UC_LOWER_U_DACUTE, 0x0000),
    DEADTRANS(UC_CURRENCY, UC_DOUBLE_ACUTE, UC_COMB_DOUBLE_ACUTE, 0x0000),
    DEADTRANS(UC_MICRO, UC_DOUBLE_ACUTE, UC_COMB_DOUBLE_ACUTE, 0x0000),
    DEADTRANS(0x017f, UC_DOUBLE_ACUTE, UC_COMB_DOUBLE_ACUTE, 0x0000),
    DEADTRANS(UC_NBSP, UC_DOUBLE_ACUTE, UC_DOUBLE_ACUTE, 0x0000),
    DEADTRANS(UC_NNBSP, UC_DOUBLE_ACUTE, UC_DOUBLE_ACUTE, 0x0000),
    DEADTRANS(L' ', UC_DOUBLE_ACUTE, UC_DOUBLE_ACUTE, 0x0000),
    DEADTRANS(L'A', 0x02f5, 0x0200, 0x0000),
    DEADTRANS(L'E', 0x02f5, 0x0204, 0x0000),
    DEADTRANS(L'I', 0x02f5, 0x0208, 0x0000),
    DEADTRANS(L'O', 0x02f5, 0x020c, 0x0000),
    DEADTRANS(L'R', 0x02f5, 0x0210, 0x0000),
    DEADTRANS(L'U', 0x02f5, 0x0214, 0x0000),
    DEADTRANS(L'a', 0x02f5, 0x0201, 0x0000),
    DEADTRANS(L'e', 0x02f5, 0x0205, 0x0000),
    DEADTRANS(L'i', 0x02f5, 0x0209, 0x0000),
    DEADTRANS(L'o', 0x02f5, 0x020d, 0x0000),
    DEADTRANS(L'r', 0x02f5, 0x0211, 0x0000),
    DEADTRANS(L'u', 0x02f5, 0x0215, 0x0000),
    DEADTRANS(UC_CURRENCY, 0x02f5, UC_COMB_DOUBLE_GRAVE, 0x0000),
    DEADTRANS(UC_MICRO, 0x02f5, UC_COMB_DOUBLE_GRAVE, 0x0000),
    DEADTRANS(0x017f, 0x02f5, UC_COMB_DOUBLE_GRAVE, 0x0000),
    DEADTRANS(UC_NBSP, 0x02f5, 0x02f5, 0x0000),
    DEADTRANS(UC_NNBSP, 0x02f5, 0x02f5, 0x0000),
    DEADTRANS(L' ', 0x02f5, 0x02f5, 0x0000),
    {0, 0, 0}
};

//---------------------------------------------------------------------------
// Main keyboard layout structure, point to all tables
//---------------------------------------------------------------------------

static KBDTABLES kbd_tables = {
    .pCharModifiers  = &char_modifiers,
    .pVkToWcharTable = vk_to_wchar,
    .pDeadKey        = dead_keys,
    .pKeyNames       = key_names,
    .pKeyNamesExt    = key_names_ext,
    .pKeyNamesDead   = key_names_dead,
    .pusVSCtoVK      = scancode_to_vk,
    .bMaxVSCtoVK     = ARRAYSIZE(scancode_to_vk),
    .pVSCtoVK_E0     = scancode_to_vk_e0,
    .pVSCtoVK_E1     = scancode_to_vk_e1,
    .fLocaleFlags    = MAKELONG(KLLF_ALTGR, KBD_VERSION),
    .nLgMax          = 0,
    .cbLgEntry       = 0,
    .pLigature       = NULL,
    .dwType          = 0,
    .dwSubType       = 0,
};

//---------------------------------------------------------------------------
// Keyboard layout entry point
//---------------------------------------------------------------------------

__declspec(dllexport) PKBDTABLES KbdLayerDescriptor(void)
{
    return &kbd_tables;
}
